### ISSUE TITLE
Plugin Errors

### ISSUE THREAD

**Issue by alfacruxis** [IndigoDomotics/indigo-yamaharx#11]
I have updated to versión 1.0.2, but upon loading the new plugin, I receive the following errors:
-----------------------------------------------------------------
   Starting plugin "Yamaha RX Receiver 1.0.2" (pid 2801)
   Started plugin "Yamaha RX Receiver 1.0.2"
   Yamaha RX Receiver Error        exception in deviceStartComm(Sintoamplificador Living): 'NoneType' object has no attribute 'text'
   Yamaha RX Receiver Error        runConcurrentThread error: 
Traceback (most recent call last):
  File "plugin.py", line 190, in runConcurrentThread
    self.updateStatus(devId)
  File "plugin.py", line 270, in updateStatus
    volume = root.find("./Main_Zone/Basic_Status/Vol/Lvl/Val").text
AttributeError: 'NoneType' object has no attribute 'text'

   Yamaha RX Receiver Error        plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   Yamaha RX Receiver Error        runConcurrentThread error: 
Traceback (most recent call last):
  File "plugin.py", line 190, in runConcurrentThread
    self.updateStatus(devId)
  File "plugin.py", line 270, in updateStatus
    volume = root.find("./Main_Zone/Basic_Status/Vol/Lvl/Val").text
AttributeError: 'NoneType' object has no attribute 'text'
-----------------------------------------------------------------

And then it repeats every 10 seconds.

I tried to downgrade to version 1.0.1, but I get the same results.
I'm working with Indigo 7.0.3 and a AV Receiver Yamaha RX-V779.
The last working plugin version seems to be 0.1.2, which I reverted to.

Any help will be appreciated.
Thanks for your time.

**Comment by indigodomo** [comment]
Unfortunately, that's in the old code (not the receiver code that I added for the vX73 line. Basically what it's saying is that the API call didn't return the volume level. My guess is that the RX-V779 slightly changed the XML protocol.

Looking at the error and the last pre V1 release available in the releases section here (0.1.1), it looks like it should be failing in that release as well. I don't know where you got the 0.1.2 release, perhaps someone fixed it in that one but it's not one of the releases here.

Is the volume actually updating using the version of the plugin you're using? I'd be surprised if it were.

**Comment by alfacruxis** [comment]
Today tried the latest version of the plug-in (1.0.3) and I'm having the same results:

   Yamaha RX Receiver Error        exception in deviceStartComm(Sintoamplificador Living): 'NoneType' object has no attribute 'text'
   Yamaha RX Receiver Error        runConcurrentThread error: 
Traceback (most recent call last):
  File "plugin.py", line 190, in runConcurrentThread
    self.updateStatus(devId)
  File "plugin.py", line 270, in updateStatus
    volume = root.find("./Main_Zone/Basic_Status/Vol/Lvl/Val").text
AttributeError: 'NoneType' object has no attribute 'text'

   Yamaha RX Receiver Error        plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

I returned once again to version 0.1.2 and is working again.
Regarding the question of if the v0.1.2 can update the volume, answer is yes, it can.
Any directions on how to plot the old code to the new plugin?

Thanks for your time.

**Comment by indigodomo** [comment]
Zip up the 0.1.2 plugin that works for you and attach it to a reply post here - I'll see if I can figure out what that version did to fix the problem.

**Comment by alfacruxis** [comment]
Hello,

Sure. Here you have it.







El 26 abr. 2018, a las 14:08, Indigo Domotics <notifications@github.com> escribió:

Zip up the 0.1.2 plugin that works for you and attach it to a reply post here - I'll see if I can figure out what that version did to fix the problem.

**Comment by indigodomo** [comment]
You have to attach it on the actual Issue on Github (https://github.com/IndigoDomotics/indigo-yamaharx/issues/11) - email attachments aren't saved AFAIK.

**Comment by alfacruxis** [comment]
Oh, sorry.
There it comes…


El 26 abr. 2018, a las 14:12, Indigo Domotics <notifications@github.com> escribió:

You have to attach it on the actual Issue on Github (#11 <https://github.com/IndigoDomotics/indigo-yamaharx/issues/11>) - email attachments aren't saved AFAIK.

**Comment by alfacruxis** [comment]
[Yamaha RX v0.1.2.zip](https://github.com/IndigoDomotics/indigo-yamaharx/files/1952250/Yamaha.RX.v0.1.2.zip)

**Comment by indigodomo** [comment]
Someone did some major work on the version you have that was never merged into the master. Turn on debug logging on the 0.1.2 version and watch for any debugging lines in the event log that start with "HTTPError" or "URLError". The version you have has additional error catching code that the newer version doesn't since those changes were never merged into the main plugin.

There is a non-trivial amount of work required to merge the 0.1.2 into the 1.x branch - I'm not going to be able to that any time soon (perhaps someone else would like to make the attempt?). But if there is a specific error that 0.1.2 is catching then I may be able to just catch that error. If you see any of those in the event log then post them here.

**Comment by alfacruxis** [comment]
Thanks for taking the time to check all that.
The version 0.1.2 has no option to turn on/off debugging in the preference setting.

**Comment by indigodomo** [comment]
It looks like debug is on all the time. Watch for those errors.

**Comment by alfacruxis** [comment]
Ok.
Will post them if they appear.
Thanks again!
